# Conversation states (shared across handler modules)
ADDING_STOCK, REMOVING_STOCK, EXCHANGE_SELECTION, WAITING_AUTH_CODE = range(4)
BACKTEST_SELECTING_SYMBOLS, BACKTEST_ENTERING_START_DATE, BACKTEST_ENTERING_END_DATE, \
BACKTEST_ENTERING_CAPITAL, BACKTEST_ENTERING_POSITION_SIZE, BACKTEST_CONFIRMING = range(4, 10)

from telegram_bot.bot_controller.app import main
